### ISSUE TITLE
implementation dependencies conflate headers and libs

### ISSUE THREAD

**Issue by lhunath** [gradle/gradle-native#743]
### Expected Behavior
Exclude directories from link libraries and exclude files from header paths.

### Current Behavior
Currently, all `implementation` dependencies on a library/binary are automatically added to `includePathConfig`, `nativeLink`, and `nativeRuntime`.  For external module dependencies, it's my understanding that these dependencies are filtered by means of the `Usage` attribute, however for `files` or `fileTree` based dependencies, this is not true.  As a consequence, all library files are added to the include path and all include folders are added as link libraries.

This obviously results in breakage at the level of the compiler/linker, library files are not directories and include paths are not files:

```
> Could not get file details of /Users/lhunath/Documents/workspace/lyndir/MasterPassword/lib/libsodium/build-macos~/out/lib/libsodium.dylib/string.h: could not stat file (errno 20: Not a directory)

Caused by: net.rubygrapefruit.platform.NativeException: Could not get file details of /Users/lhunath/Documents/workspace/lyndir/MasterPassword/lib/libsodium/build-macos~/out/lib/libsodium.dylib/string.h: could not stat file (errno 20: Not a directory)
        at net.rubygrapefruit.platform.internal.DefaultPosixFiles.stat(DefaultPosixFiles.java:38)
        at net.rubygrapefruit.platform.internal.DefaultPosixFiles.stat(DefaultPosixFiles.java:25)
        at org.gradle.internal.nativeintegration.filesystem.services.NativePlatformBackedFileMetadataAccessor.stat(NativePlatformBackedFileMetadataAccessor.java:38)
        at org.gradle.internal.nativeintegration.filesystem.services.GenericFileSystem.stat(GenericFileSystem.java:82)
        at org.gradle.api.internal.changedetection.state.DefaultFileSystemSnapshotter.calculateDetails(DefaultFileSystemSnapshotter.java:230)
        at org.gradle.api.internal.changedetection.state.DefaultFileSystemSnapshotter.access$100(DefaultFileSystemSnapshotter.java:60)
        at org.gradle.api.internal.changedetection.state.DefaultFileSystemSnapshotter$1.create(DefaultFileSystemSnapshotter.java:98)
        at org.gradle.api.internal.changedetection.state.DefaultFileSystemSnapshotter$1.create(DefaultFileSystemSnapshotter.java:93)
        at org.gradle.cache.internal.ProducerGuard$StripedProducerGuard.guardByKey(ProducerGuard.java:115)
        at org.gradle.api.internal.changedetection.state.DefaultFileSystemSnapshotter.snapshotSelf(DefaultFileSystemSnapshotter.java:93)
        at org.gradle.language.nativeplatform.internal.incremental.DefaultSourceIncludesResolver.searchForDependency(DefaultSourceIncludesResolver.java:277)
        at org.gradle.language.nativeplatform.internal.incremental.DefaultSourceIncludesResolver.access$300(DefaultSourceIncludesResolver.java:42)
        at org.gradle.language.nativeplatform.internal.incremental.DefaultSourceIncludesResolver$PathResolvingVisitor.visitSystem(DefaultSourceIncludesResolver.java:457)
        at org.gradle.language.nativeplatform.internal.incremental.DefaultSourceIncludesResolver.resolveExpression(DefaultSourceIncludesResolver.java:62)
        at org.gradle.language.nativeplatform.internal.incremental.DefaultSourceIncludesResolver.resolveInclude(DefaultSourceIncludesResolver.java:56)
        at org.gradle.language.nativeplatform.internal.incremental.IncrementalCompileFilesFactory$DefaultIncementalCompileSourceProcessor.visitFile(IncrementalCompileFilesFactory.java:142)
        at org.gradle.language.nativeplatform.internal.incremental.IncrementalCompileFilesFactory$DefaultIncementalCompileSourceProcessor.visitSourceFile(IncrementalCompileFilesFactory.java:100)
        at org.gradle.language.nativeplatform.internal.incremental.IncrementalCompileFilesFactory$DefaultIncementalCompileSourceProcessor.processSource(IncrementalCompileFilesFactory.java:83)
        at org.gradle.language.nativeplatform.internal.incremental.IncrementalCompileProcessor$1.call(IncrementalCompileProcessor.java:45)
        at org.gradle.language.nativeplatform.internal.incremental.IncrementalCompileProcessor$1.call(IncrementalCompileProcessor.java:39)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:331)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:321)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:107)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.language.nativeplatform.internal.incremental.IncrementalCompileProcessor.processSourceFiles(IncrementalCompileProcessor.java:39)
```

### Context
I have a library which is built using autotools.  I need to add its output library to the `nativeLink` and its headers to the `includePathConfig`.

### Steps to Reproduce (for bugs)
```
        dependencies {
            implementation files( "$rootDir/../lib/libsodium/src/libsodium/include" )
            implementation fileTree( "$rootDir/../lib/libsodium/build/out/lib" )
        }
```

### Your Environment
 * Build scan URL: 
https://gradle.com/s/ziub4aaqgcy4a

**Comment by lhunath** [comment]
I can probably move the headers dependency into `privateHeaders` like so:

```
        privateHeaders {
            from files( "$rootDir/../lib/libsodium/src/libsodium/include" )
        }
```

But I see no way of doing this for the link library.  And regardless of whether there's a work-around, the current behavior of `implementation` is definitely buggy (and clearly written with the assumption that dependencies will always be `ExternalModuleDependency`s).  An issue which is also visible in the method signature of `#implementation(Object, org.gradle.api.Action<? super ExternalModuleDependency>)` in `org.gradle.language.ComponentDependencies`.

**Comment by big-guy** [comment]
Hi @lhunath,

I think this is "working as designed", but it's not great. We shouldn't fail with such an odd error (opened https://github.com/gradle/gradle-native/issues/762). Adding files or file paths to dependencies like this is inherently lossy since we don't know in which context the files should or should not be used.

I think we would tackle this a slightly different way. We want some kind of identity/metadata about dependencies so we can show useful information about dependencies (conflicts, version changes, etc) or keep transitive dependencies straight.

An alternative that's closest to what you're doing now, you can add the right paths to the underlying configurations yourself:
https://github.com/gradle/native-samples/blob/master/cpp/prebuilt-binaries/build.gradle#L52-L64

This keeps the include path and the libraries separate.

We have a (more involved) sample that creates a C++ library model in Gradle, but uses autotools to build things:
https://github.com/gradle/native-samples#libraries-build-with-autotools-autotools-library

This allows you to use project dependencies in the build instead of manually adding paths. This is something we want to build into Gradle eventually.

HTH
