### ISSUE TITLE
More performance from smaller <max-workers> ?

### ISSUE THREAD

**Issue by ghale** [gradle/gradle-native#852]
@mathjeff commented on [Tue Aug 28 2018](https://github.com/gradle/gradle/issues/6545)

I made the interesting observation on my computer (having 56 cores) that a clean build of AndroidX using `--max-workers=16` runs much faster than a clean build without any specification of `--max-workers`.

I've also discovered that according to `pstree -p ${gradlePid} | wc -l`, Gradle has 8000-10000 child processes in existence at a time.

I've also found that even with only "--max-workers=16", according to `htop`, Gradle generally uses more than 99% of all of the CPUs

My guess is that what's going on is that Gradle (specifically, probably one or more Gradle plugins) is spawning many more processes than is needed, and that that's resulting in excess context switching.

I'm not sure whether this is something that Gradle can reasonably be expected to dynamically detect and compensate for, but if it is then that would be handy.

I'm still hoping to dig deeper into the details eventually to figure out more specifically why so many processes are spawning.

I enabled build scans for two representative builds, which can be found at:
Build scan from max-workers 16         : https://scans.gradle.com/s/fknlr375evb4o
Build scan from max-workers unspecified: https://scans.gradle.com/s/mmkeof2zrjxcy

To reproduce this behavior:
1. download the androidx-master-dev branch of AndroidX via `repo` as described in https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-master-dev/README.md
2. run `cd frameworks/support && rm -rf ../../out && GRADLE_USER_HOME../../out ./gradlew buildOnServer`

Some additional build durations for other values of --max-workers :

--max-workers=8 buildOnServer
9.37user 11.74system 12:42.06elapsed 2%CPU (0avgtext+0avgdata 383932maxresident)k
32inputs+319152outputs (0major+98306minor)pagefaults 0swaps

--max-workers=16 buildOnServer
9.02user 10.86system 11:22.92elapsed 2%CPU (0avgtext+0avgdata 409428maxresident)k
0inputs+319088outputs (0major+103593minor)pagefaults 0swaps

--max-workers=24 buildOnServer
9.28user 11.56system 12:06.81elapsed 2%CPU (0avgtext+0avgdata 499748maxresident)k
0inputs+319192outputs (0major+128482minor)pagefaults 0swaps

--max-workers=32 buildOnServer
11.05user 12.31system 13:57.19elapsed 2%CPU (0avgtext+0avgdata 579620maxresident)k
0inputs+319256outputs (0major+152748minor)pagefaults 0swaps

--max-workers=40 buildOnServer
12.42user 12.18system 15:00.71elapsed 2%CPU (0avgtext+0avgdata 576896maxresident)k
0inputs+319280outputs (0major+150236minor)pagefaults 0swaps

--max-workers=48 buildOnServer
11.77user 11.93system 17:40.43elapsed 2%CPU (0avgtext+0avgdata 616720maxresident)k
0inputs+319408outputs (0major+157018minor)pagefaults 0swaps

--max-workers=56 buildOnServer
12.91user 12.34system 23:53.76elapsed 1%CPU (0avgtext+0avgdata 631672maxresident)k
0inputs+319552outputs (0major+160298minor)pagefaults 0swaps

--max-workers=64 buildOnServer
14.16user 13.41system 26:04.43elapsed 1%CPU (0avgtext+0avgdata 653612maxresident)k
0inputs+319776outputs (0major+165561minor)pagefaults 0swaps

Anyway, I'm not necessarily expecting a specific solution from Gradle ; mostly just trying to raise awareness

Thanks

---

@oehme commented on [Wed Aug 29 2018](https://github.com/gradle/gradle/issues/6545#issuecomment-416851048)

Having thousands of child processes is definitely not normal. Gradle itself will only allow `--max-workers` "things" to run at any given time. Have you checked what some of these processes are doing? Maybe we can narrow down the culprit that way.

---

@mathjeff commented on [Fri Sep 14 2018](https://github.com/gradle/gradle/issues/6545#issuecomment-421461382)

Slight clarification/correction to my previous statement, it turns out that the >8000 number that I computed from `pstree -p ${gradlePid} | wc -l` was actually threads, not processes.

Now it turns out that based on `jstack -l ${gradlePid} | grep 'ForkJoinPool-' | wc -l`, it looks like there are 5445 ForkJoinPool workers. Most of the blocks of output from jstack look like:

"ForkJoinPool-10488-worker-56" #20122 daemon prio=5 os_prio=0 tid=0x00007f351c055000 nid=0x15718 waiting on condition [0x00007f2d22dec000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000006d0a73b50> (a java.util.concurrent.ForkJoinPool)
        at java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1824)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1693)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

   Locked ownable synchronizers:
        - None

I don't see very many instances of the text "ForkJoinPool" in the source code of Gradle but I do see a bunch of instances in the source code of the Android Gradle Plugin so I guess that's probably where I'll look next

---

@oehme commented on [Fri Sep 14 2018](https://github.com/gradle/gradle/issues/6545#issuecomment-421463538)

Make sure you're using the latest Gradle version. There was a Thread leak that we fixed in 4.10.

---

@mathjeff commented on [Mon Sep 17 2018](https://github.com/gradle/gradle/issues/6545#issuecomment-422138853)

Thanks - we're now upgrading from 4.9 to 4.10 .

Some more evidence that seems consistent with a thread leak is the fact that the number of threads (reported by `pstree -l -a $gradlePid`) seems to grow slowly from roughly 200 to >8000.

The high thread count does appear to be happening with Gradle 4.10 (in fact, with Gradle 4.10 it seems to max out at a higher number of threads: 13199) ; hopefully I'll be able to look closer eventually. For now I've uploaded a build scan using Gradle 4.10 to https://gradle.com/s/g3mna6ihz63y6

The output from `pstree -l -a $gradlePid` at the point where there are 13199 java threads is:

  java -Dorg.gradle.appname=gradlew -classpath /usr/local/google/workspace/aosp-androidx/frameworks/support/gradle/wrapper/gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain --max-workers 16 buildOnServer --scan
    ├─java -Xmx4g -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp /usr/local/google/workspace/aosp-androidx/out/wrapper/dists/gradle-4.10-bin/bg6py687nqv2mbe6e1hdtk57h/gradle-4.10/lib/gradle-launcher-4.10.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 4.10
    │   ├─aapt2 m
    │   ├─aapt2 m
    │   ├─aapt2 m
    │   ├─aapt2 m
    │   ├─aapt2 m
    │   ├─aapt2 m
    │   ├─aapt2 m
    │   ├─aapt2 m
    │   ├─aapt2 m
    │   ├─aapt2 m
    │   ├─aapt2 m
    │   ├─aapt2 m
    │   ├─aapt2 m
    │   ├─aapt2 m
    │   ├─aapt2 m
    │   ├─aapt2 m
    │   ├─java -cp /usr/local/google/workspace/aosp-androidx/out/caches/jars-3/296ec0d5efe8a424adf9c360ddcdef73/kotlin-compiler-embeddable-1.2.50.jar:/usr/local/google/workspace/aosp-androidx/out/caches/jars-3/3acc749bd7d84927a5b32329a5411480/kotlin-stdlib-1.2.50.jar:/usr/local/google/workspace/aosp-androidx/out/caches/jars-3/8a0018227a194666460618fdabe33fae/kotlin-script-runtime-1.2.50.jar:/usr/local/google/workspace/aosp-androidx/out/caches/jars-3/67ebf2f2d81e5e20709d078721290562/kotlin-reflect-1.2.50.jar:/usr/local/google/workspace/aosp-androidx/out/caches/jars-3/943c1d6286bb7965f2148fb360afe1e0/kotlin-scripting-common-1.2.50.jar:/usr/local/google/workspace/aosp-androidx/out/caches/jars-3/4c597df235d698cd4ccdb7dbb4d26ce3/kotlin-scripting-jvm-1.2.50.jar:/usr/local/google/workspace/aosp-androidx/out/caches/jars-3/5803fd6aa19608e89d677a2f6892283b/kotlinx-coroutines-core-0.20.jar:/usr/local/google/workspace/android-master/prebuilts/jdk/jdk8/linux-x86/lib/tools.jar -Djava.awt.headless=true -Djava.rmi.server.hostname=127.0.0.1 -Xmx4g -Dkotlin.environment.keepalive org.jetbrains.kotlin.daemon.KotlinCompileDaemon --daemon-runFilesPath /usr/local/google/home/jeffrygaston/.local/share/kotlin/daemon --daemon-autoshutdownIdleSeconds=7200 --daemon-compilerClasspath /usr/local/google/workspace/aosp-androidx/out/caches/jars-3/296ec0d5efe8a424adf9c360ddcdef73/kotlin-compiler-embeddable-1.2.50.jar:/usr/local/google/workspace/aosp-androidx/out/caches/jars-3/3acc749bd7d84927a5b32329a5411480/kotlin-stdlib-1.2.50.jar:/usr/local/google/workspace/aosp-androidx/out/caches/jars-3/8a0018227a194666460618fdabe33fae/kotlin-script-runtime-1.2.50.jar:/usr/local/google/workspace/aosp-androidx/out/caches/jars-3/67ebf2f2d81e5e20709d078721290562/kotlin-reflect-1.2.50.jar:/usr/local/google/workspace/aosp-androidx/out/caches/jars-3/943c1d6286bb7965f2148fb360afe1e0/kotlin-scripting-common-1.2.50.jar:/usr/local/google/workspace/aosp-androidx/out/caches/jars-3/4c597df235d698cd4ccdb7dbb4d26ce3/kotlin-scripting-jvm-1.2.50.jar:/usr/local/google/workspace/aosp-androidx/out/caches/jars-3/5803fd6aa19608e89d677a2f6892283b/kotlinx-coroutines-core-0.20.jar:/usr/local/google/workspace/android-master/prebuilts/jdk/jdk8/linux-x86/lib/tools.jar
    │   │   └─99*[{java}]
    │   └─13199*[{java}]
    └─64*[{java}]

---

@oehme commented on [Mon Sep 17 2018](https://github.com/gradle/gradle/issues/6545#issuecomment-422175666)

@ghale can you take a look at this one? Not sure if this is a bug in the worker API or a bug in AAPT.

**Comment by ghale** [comment]
Comments about findings are on the original issue.
